os:
  - linux
  - osx
sudo: false
language: node_js
before_install:
  - export JOBS=max
node_js:
  - 10
  - 12
  - lts/*
  - current
notifications:
  email:
    - rod@vagg.org
install: npm install
script: npm test
