environment:
  node_pre_gyp_accessKeyId:
    secure: 7DrSVc5eIGtmMcki5H+iRft+Tk3MJTwDBQEUuJHWaQ4=
  node_pre_gyp_secretAccessKey:
    secure: 1amwJJw9fu0j6dXnc5KsAQbSYf7Cjw/dapT6OZWABa6nc52grkKeLQ+DGaOfQz8i
  matrix:
    - nodejs_version: 0.10.45
      platform: x86
      msvs_toolset: 12
    - nodejs_version: 0.10.45
      platform: x64
      msvs_toolset: 12
    - nodejs_version: 0.12.14
      platform: x86
      msvs_toolset: 12
    - nodejs_version: 0.12.14
      platform: x64
      msvs_toolset: 12
    - nodejs_version: 4.4.5
      platform: x64
      msvs_toolset: 12
    - nodejs_version: 4.4.5
      platform: x86
      msvs_toolset: 12
    - nodejs_version: 6.2.1
      platform: x64
      msvs_toolset: 12
    - nodejs_version: 6.2.1
      platform: x86
      msvs_toolset: 12

install:
  - ps: Install-Product node $env:nodejs_version
  - npm -g install npm
  - npm install

test_script:
  - node --version
  - npm --version
  - npm test

# Don't actually build.
build: off

# Set build version format here instead of in the admin panel.
version: "{build}"
